version: '3'
services:
  web:
    build:
      context: ./api
    command: gunicorn app.main:app --workers=4 --bind 0.0.0.0:5000 --reload
    volumes:
      - ./api:/app
    ports:
      - "5005:5000"
    environment:
      - TWITTER_CONSUMER_KEY=${TWITTER_CONSUMER_KEY}
      - TWITTER_CONSUMER_SECRET=${TWITTER_CONSUMER_SECRET}
